### ISSUE TITLE
Can't leave ssh connection page

### ISSUE THREAD

**Issue by BrunoMiguens** [ledokku/ledokku#271] opened 2021-02-25 13:46 UTC
# Bug report

## Describe the bug

Just finished the setup using the bootstrap and everything worked fine, however, the ssh connection page never leaves and I did already registered the ssh-key provided in that same page.

<img width="809" alt="Screenshot 2021-02-25 at 13 46 34" src="https://user-images.githubusercontent.com/6075268/109162233-e1e6b300-776f-11eb-8755-2f6cfffeccc3.png">

I have this two ssh key added:

```
SHA256:... NAME="admin1" ...
SHA256:... NAME="ledokku" ...
```

**Comment by Akirtovskis** [comment] 2021-02-25 16:41
Hey @BrunoMiguens , thanks for reaching out! 

Firstly, just as a sanity check, did you refresh the page after running the ssh script on your server?

Secondly, I just did tried to replicate this by creating fresh docker droplet on digital ocean, installing dokku and then Ledokku and was not able to replicate the issue. 

Do you see any sort of output during `ledokku` bootstrap script that could be helpful?  

What is the version of `dokku` do you have? 

@pradel maybe you have any ideas?

**Comment by BrunoMiguens** [comment] 2021-02-25 17:18
Yeah I did refresh multiple times the page.

I used the digital ocean deploy image of dokku (0.23.8).

Didn't spot any error whatsoever on bootstrap

**Comment by Akirtovskis** [comment] 2021-02-25 17:32
Could you try using docker droplet instead of dokku one? 

It adds an extra step of installing dokku on the server, but I have high confidence that this will work as I have done it already multiple times in the past days. 

Nevertheless we will look into why it didn't work with the dokku one, thanks for catching this.

**Comment by BrunoMiguens** [comment] 2021-02-25 18:11
Destroyed the last droplet, used the docker form the marketplace on Digital Ocean, followed all the steps on your getting started and everything was installed well, but the problem continues.

I did add the ssh key exactly how you mentioned on the page , reloaded and nothing new, unfortunately.

**Comment by Akirtovskis** [comment] 2021-02-25 21:15
Thanks for giving this multiple tries, I will try to replicate this tomorrow and get back to you then.

**Comment by Akirtovskis** [comment] 2021-02-26 09:38
@BrunoMiguens this is indeed strange. I just tried fresh  `Docker` droplet, everything worked as expected and same was for `Dokku` droplet as well. 

Are you sure you are not missing anything from the getting started guide? Perhaps it is worth trying the flow with newly created ssh?

**Comment by pradel** [comment] 2021-02-26 11:06
@BrunoMiguens we will release a new version soon that will add more logs to see what's going on, we will ping you when it's ready :)

**Comment by BrunoMiguens** [comment] 2021-02-26 11:11
@Akirtovskis Yeah perhaps regenerating the ssh would work, I might try.

@pradel That would be amazing and would possibly avoid creating issues on Github that are probably not issues, like mine 😅

**Comment by pradel** [comment] 2021-02-26 11:31
@BrunoMiguens can you try with v0.5.1? If you start with a new server you can do it as usual or you can also upgrade the current one you have (docs: https://www.ledokku.com/docs/upgrade/).
In order to see the logs you will need to set the `DEBUG` env variable value to `queries:*`. Then your server should restart,  after this just reload the client page and the error should appear in the server logs :)

**Comment by pillows** [comment] 2021-03-06 00:16
`2021-03-06T00:13:53.015163881Z app[web.1]: yarn run v1.22.5
2021-03-06T00:13:53.056599420Z app[web.1]: $ yarn prisma:migrate && node build/index.js
2021-03-06T00:13:53.241683999Z app[web.1]: $ prisma migrate up --experimental
2021-03-06T00:13:53.735597864Z app[web.1]: 
2021-03-06T00:13:54.260994957Z app[web.1]: Prisma schema loaded from prisma/schema.prisma
2021-03-06T00:13:54.408645297Z app[web.1]: 🏋️‍  migrate up
2021-03-06T00:13:54.408664401Z app[web.1]: 
2021-03-06T00:13:54.409014804Z app[web.1]: All migrations are already applied
2021-03-06T00:13:55.305978659Z app[web.1]: 🚀 Server ready at http://localhost:4000/graphql
2021-03-06T00:13:55.306112384Z app[web.1]: 🚀 Subscriptions ready at ws://localhost:4000/graphql
2021-03-06T00:14:26.903904034Z app[web.1]: 2021-03-06T00:14:26.903Z queries:setup Error: connect EADDRNOTAVAIL [MY IPV6 ADDRESS] - Local (:::0)
2021-03-06T00:14:26.903930897Z app[web.1]:     at internalConnect (net.js:923:16)
2021-03-06T00:14:26.903936539Z app[web.1]:     at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
2021-03-06T00:14:26.903940692Z app[web.1]:     at net.js:1011:9
2021-03-06T00:14:26.903944177Z app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
`

I'm having the same issue too but I believe that it may be because of the ipv6 address that it defaults to.

**Comment by Akirtovskis** [comment] 2021-03-06 18:51
@pillows thanks for reaching out and thanks for posting the fix. 🙏 

Perhaps @BrunoMiguens this could work for you as a temporary fix as well? 

I will create an issue so the problem is fixed permanently at some point soon.

**Comment by cb1kenobi** [comment] 2021-03-07 07:50
I just ran into this issue. Same environment as listed above. I can confirm IPv6 is the culprit. Huge thanks to @pillows!

**Comment by pillows** [comment] 2021-03-07 07:52
Honestly could not have found the culprit without @pradel 's comment about the DEBUG env variable.

**Comment by pradel** [comment] 2021-03-07 11:48
@Akirtovskis as it seems like a few people have this issue we should probably improve the server logs if the `DOKKU_SSH_HOST` is not an ipv4

**Comment by pradel** [comment] 2021-03-07 12:26
@pillows @cb1kenobi did you install ledokku using the install script or did you do the manual installation?

**Comment by pradel** [comment] 2021-03-07 12:34
Created a pr to force the ip to resolve to ipv4 for the installation script https://github.com/ledokku/ledokku/pull/291

**Comment by pradel** [comment] 2021-03-07 12:37
Closing the issue as this is now fixed on master, will be live with the next release!

**Closed by pradel** 2021-03-07 12:37 UTC
Labels: bug
